app/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
    path('leaderboard/', include('top.urls', namespace='top')),
]

main/urls.py
from django.contrib import admin
from django.urls import path

from main import views

app_name = 'main '

urlpatterns = [
    path('', views.index, name='index'),
]

top/urls.py
from django.contrib import admin
from django.urls import path, include

from top import views 

app_name = 'top'

urlpatterns = [
    path('', views.top, name='leaderboard'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views 

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update_profile/', views.add_symbols, name='update_profile'),
    path('link_telegram/', views.link_telegram, name='link_telegram'),
    path('unlink_telegram/', views.unlink_telegram, name='unlink_telegram'),
]

top/models.py
from django.db import models

# Create your models here.

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    symbols_typed = models.PositiveIntegerField(default=0, verbose_name="Total symbols typed")
    telegram_id = models.CharField(max_length=32, blank=True, null=True)
    telegram_token = models.UUIDField(default=uuid.uuid4, unique=True, null=True, blank=True)
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self) -> str:
        return self.username
    





class Attemp(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE, verbose_name="Пользователь", blank=True, null=True
    )
    wpm = models.PositiveSmallIntegerField(default=0)
    accuracy = models.PositiveSmallIntegerField(default=0)
    error_cnt = models.PositiveSmallIntegerField(default=0)
    mode = models.CharField(max_length=16, null=True, blank=True)
    attemp_time = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата добавления"
    )

users/forms.py
import re
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]
    
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context={
       'title' : 'Type' 
    }
    return render(request,'main/index.html', context)

top/views.py
from django.http import JsonResponse
from django.shortcuts import render
from users.models import User
from django.template.loader import render_to_string
# Create your views here.

def top(request):
    top_users = User.objects.order_by('-symbols_typed')[:100]
    context = {
       'top_users': top_users,
    }
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        html = render_to_string('top/leaderboard_ajax.html', context)
        return JsonResponse({'html': html})

    return render(request, 'top/leaderboard.html', context)

users/views.py
import uuid
from xml.sax.xmlreader import AttributesImpl
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import context
from django.urls import reverse

from users.forms import UserLoginForm, UserRegistrationForm
from users.models import Attemp, User
from django.core.management import call_command

# Create your views here.


def login(request):
    if request.method == 'POST':
        if 'login' in request.POST:
            form = UserLoginForm(data=request.POST)
            if form.is_valid():
                username = request.POST['username']
                password = request.POST['password']
                user = auth.authenticate(username=username, password=password)
                if user:
                    auth.login(request, user)
                    return HttpResponseRedirect(reverse('main:index'))
        elif 'register' in request.POST:
            form = UserRegistrationForm(data=request.POST)
            if form.is_valid():
                form.save()
                user = form.instance
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
        else:
            form = UserLoginForm()
    else:
        form = UserLoginForm()

    context = {
        'title': 'login',
        'form': form
    }
    return render(request, 'users/login.html', context)

@login_required
def profile(request):
    attemps = Attemp.objects.filter(user=request.user).order_by('-attemp_time')
    telegram_id = request.user.telegram_id
    context = {
        'title': 'profile',
        'attemps':attemps,
        'telegram_id':telegram_id,
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))


def add_symbols(request):
    if request.method == 'POST':
        lettersTyped = int(request.POST.get("lettersTyped", 0)) 
        if request.user.is_authenticated:
            user = get_object_or_404(User, username=request.user.username)
            user.symbols_typed += lettersTyped
            if "wpm" not in request.POST:
                user.save()
                return JsonResponse({'success': True})
            wpm = int(request.POST.get("wpm", 0)) 
            accuracy = int(request.POST.get("accuracy", 0))
            error_cnt = int(request.POST.get("error_cnt", 0))
            mode = request.POST.get("mode", "")
            attemp_instance = Attemp.objects.create(user=user,
                                                            wpm=wpm,
                                                            accuracy=accuracy,
                                                            error_cnt=error_cnt,
                                                            mode=mode
                                                            )
            attemp_instance.save()
            user.save()
            if user.telegram_id:
                count = Attemp.objects.filter(user__username=request.user.username).count()
                call_command('send_attemp', user.telegram_id, f"{request.user.username}\n🟡Attemp {count}\n⚫mode: {mode}\n🟡WPM: {wpm}\n⚫ACC: {accuracy/100}%\n🟡ERR: {error_cnt}")
            return JsonResponse({'success': True})  # Ответ в формате JSON
        else:
            return JsonResponse({'success': False, 'error': 'User is not authentica ted'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})


from django.shortcuts import redirect

@login_required
def link_telegram(request):
    user = request.user
    if not user.telegram_token:
        user.telegram_token = uuid.uuid4()
        user.save()
    
    telegram_link = f"https://t.me/typetesting_bot?start={user.telegram_token}"
    return redirect(telegram_link)


@login_required
def unlink_telegram(request):
    user = request.user
    user.telegram_id = None
    user.save()
    return redirect(reverse('users:profile'))

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="icon" href="{% static "deps/icons/site_icon.svg" %}" type="image/svg+xml">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    {% block css %}
    {% endblock css %}
</head>

<body>
    <header>
        <nav class="navbar mx-5">
            <a class="navbar-brand" href="{% url "main:index" %}">
                <i class="fa-solid fa-keyboard"></i>
                Type
            </a>
            <a class="nav-link navbar-center" id="leaderboard" href="leaderboard.html">
                <i class='fas fa-crown'></i>
            </a>
            
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" id="profile" href="profile.html">
                        <i class="fas fa-user"></i>
                        Ares
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="login" href="register_login.html">
                        <i class="fa-solid fa-right-to-bracket"></i>
                    </a>
                </li>

            </ul>
        </nav>
    </header>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://kit.fontawesome.com/1cc62347df.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static "deps/js/typing.js" %}"></script>
</body>

</html>

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static "deps/css/styles.css" %}">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <nav class="navbar navbar-expand" id="modePanel">
            <div class="navbar-nav" id="modifiers">
                <a class="nav-item nav-link" href="#" id="keyboardModifier"><i class="fa-solid fa-keyboard"></i></a>
                <a class="nav-item nav-link" href="#" id="handModifier"><i class="fa-solid fa-hand"></i></a>
            </div>
            <div class="navbar-nav">
                <div class="navbar-divider"></div>
                <a class="nav-item nav-link" href="#" id="timeMode"><i class="fa-solid fa-clock"></i> time</a>
                <a class="nav-item nav-link" href="#" id="wordsMode"><i class="fa-solid fa-font"></i> words</a>
                <a class="nav-item nav-link" href="#" id="learnMode"><i class="fa-solid fa-brain"></i> learn</a>
            </div>
            <div class="navbar-nav" id="additional-buttons" style="display: none;">
                <div class="navbar-divider"></div>
                <a class="nav-item nav-link" href="#" id="cnt10">10</a>
                <a class="nav-item nav-link" href="#" id="cnt25">25</a>
                <a class="nav-item nav-link" href="#" id="cnt100">100</a>
            </div>
        </nav>
        <div id="typingTest" class="col-12" tabindex="0">
            <div id="cursor"></div>
            <div id="focus-error">Click here to focus</div>
            <div id="info"></div>
            <div id="wordsContainer">
                <div id="words"></div>
            </div>
            <div class="d-flex justify-content-center">
                <button id="newGameButton" class="mt-5" data-url="{% url 'users:update_profile' %}">
                    {% csrf_token %}
                    <i class="fa-solid fa-rotate-right"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="keyboard" id="keyboard" style="display: none;">
        <div class="key tab" id="key_tab">Tab</div>
        <div class="key" id="key_q">Q</div>
        <div class="key" id="key_w">W</div>
        <div class="key" id="key_e">E</div>
        <div class="key" id="key_r">R</div>
        <div class="key" id="key_t">T</div>
        <div class="key" id="key_y">Y</div>
        <div class="key" id="key_u">U</div>
        <div class="key" id="key_i">I</div>
        <div class="key" id="key_o">O</div>
        <div class="key" id="key_p">P</div>
        <div class="key" id="key_[">[</div>
        <div class="key" id="key_]">]</div>
        <div class="key" id="key_\">\</div>
        <div class="key capsLk" id="key_caps">Caps</div>
        <div class="key" id="key_a">A</div>
        <div class="key" id="key_s">S</div>
        <div class="key" id="key_d">D</div>
        <div class="key" id="key_f">F</div>
        <div class="key" id="key_g">G</div>
        <div class="key" id="key_h">H</div>
        <div class="key" id="key_j">J</div>
        <div class="key" id="key_k">K</div>
        <div class="key" id="key_l">L</div>
        <div class="key" id="key_;">;</div>
        <div class="key" id="key_'">'</div>
        <div class="key enter" id="key_enter">Enter</div>
        <div class="key shift" id="key_shift">Shift</div>
        <div class="key" id="key_z">Z</div>
        <div class="key" id="key_x">X</div>
        <div class="key" id="key_c">C</div>
        <div class="key" id="key_v">V</div>
        <div class="key" id="key_b">B</div>
        <div class="key" id="key_n">N</div>
        <div class="key" id="key_m">M</div>
        <div class="key" id="key_,">,</div>
        <div class="key" id="key_.">.</div>
        <div class="key" id="key_/">/</div>
        <div class="key shift" id="key_shift">Shift</div>
        <div class="key space" id="key_ ">Space</div>
    </div>
    <div class="hand" id="hand" style="display: none;"><img src="{% static "deps/images/hands/right_1.png" %}" alt="" id="handImage"></i></div>
</div>
{% endblock content %}

{% block script %} <script src="{% static "deps/js/typing.js" %}"></script>{% endblock script %}


{% block buttons %}
<li class="nav-item">              
    {% if user.is_authenticated %}
        <a class="nav-link" id="profile" href="{% url "users:profile" %}">
            <i class="fas fa-user"></i>
            {{user.username}}
        </a>
    {% else %}
        <a class="nav-link" id="login" href="{% url "users:login" %}">
            <i class="fa-solid fa-right-to-bracket"></i>
        </a>
    {% endif %}
</li>
{% endblock buttons %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="icon" href="{% static "deps/icons/site_icon.svg" %}" type="image/svg+xml">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    {% block css %}
    {% endblock css %}
</head>

<body>
    <header>
        <nav class="navbar mx-5">
            <a class="navbar-brand" href="{% url "main:index" %}">
                <i class="fa-solid fa-keyboard"></i>
                Type
            </a>
            <a class="nav-link navbar-center" id="leaderboard" href="{% url "top:leaderboard" %}">
                <i class='fas fa-crown'></i>
            </a>
            
            <ul class="nav">
                {% block buttons %}
                {% endblock buttons %}
                
                

            </ul>
        </nav>
    </header>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://kit.fontawesome.com/1cc62347df.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
   {% block script %}{% endblock script %}
</body>

</html>

top/templates/top/leaderboard.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "deps/css/styles_leaderboard.css" %}">
{% endblock css %}

{% block buttons %}
{% if user.is_authenticated %}
    <a class="nav-link" id="profile" href="{% url "users:profile" %}">
        <i class="fas fa-user"></i>
        {{user.username}}
    </a>
{% else %}
    <a class="nav-link" id="login" href="{% url "users:login" %}">
        <i class="fa-solid fa-right-to-bracket"></i>
    </a>
{% endif %}
{% endblock buttons %}


{% block content %}
<div class="row mx-auto">
    <div class="col-md-6 mx-auto">
        <table class="table table-borderless custom-table mt-5" id="leaderboard-table" data-url="{% url 'top:leaderboard' %}">
            <thead>
                <tr>
                    <th><i class="fas fa-user"></i></th>
                    <th>Symbols Typed</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                {% for top_user in top_users %}
                <tr>
                    <td>{{top_user.username}}</td>
                    <td>{{top_user.symbols_typed}}</td>
                    <td>27 Aug 2023 16:24</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static "deps/js/leaderboard.js" %}"></script>
{% endblock script %}
    

top/templates/top/leaderboard_ajax.html
{% for top_user in top_users %}
<tr>
    <td>{{ top_user.username }}</td>
    <td>{{ top_user.symbols_typed }}</td>
    <td>27 Aug 2023 16:24</td>
</tr>
{% endfor %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/styles_register.css" %}">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <!-- Форма регистрации -->
            <div class="form-box mx-auto">
                <h2 class="text-center">Register</h2>
                <form action="{% url "user:login" %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="username"
                        class="form-control register" id="id_username" placeholder="username">
                    </div>
                    <div class="form-group">
                        <input type="email" name="email"
                        class="form-control register" id="id_email" placeholder="email">
                        {% if form.email.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="password" name="password1"
                        class="form-control register" id="id_password1" placeholder="password">
                        {% if form.password1.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="password" name="password2"
                        class="form-control register" id="id_password2" placeholder="verify password">
                        {% if form.password2.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                        {% endif %}
                    </div>
                    <button name="register" type="submit" class="btn btn-block" id="register-button" disabled><i class="fa-solid fa-user-plus"></i> Sign Up</button>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <!-- Форма входа -->
            <div class="form-box mx-auto">
                <h2 class="text-center">Login</h2>
                <form action="{% url "user:login" %}" method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <input type="text" class="form-control login" name="username" id="id_username_"  placeholder="username" required>

                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control login" name="password" id="id_password" placeholder="password" required>
                        {% if form.password.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.password.errors}}</div>
                        {% endif %}
                    </div>
                    <button name="login" type="submit" class="btn btn-block" id="login-button" disabled ><i class="fa-solid fa-right-to-bracket"></i> Sign In</button> 
               
                </form> 
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block script %} 
<script src="{% static "deps/js/register_scripts.js" %}"></script>
{% endblock script %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/styles_profile.css" %}">
{% endblock css %}

{% block content %}
<div class="row mx-auto">
    <div class="col-md-6  mx-auto">
        <table class="table table-borderless custom-table mt-5">
            <thead>
                <tr>
                    <th><i class="fas fa-user"></i></th>
                    <th>Symbols Typed</th>
                    <th>Typing Time</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{user.username}}</td>
                    <td>{{user.symbols_typed}}</td>
                    <td>0:50</td>
                </tr>
            </tbody>
        </table>
        
    </div>
</div>
<div class="row mx-5">
    <div class="col-md-6 mx-auto"> <!-- Центрируем содержимое в первой колонке -->
        <table class="table table-borderless custom-table">
            <thead>
                <tr>
                    <th>10 seconds</th>
                    <th>25 seconds</th>
                    <th>100 seconds</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-md-6 mx-auto"> <!-- Центрируем содержимое во второй колонке -->
        <table class="table table-borderless custom-table">
            <thead>
                <tr>
                    <th>10 words</th>
                    <th>25 words</th>
                    <th>100 words</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="row mx-auto">
    <div class="col-md-6  mx-auto">
        <table class="table table-borderless custom-table">
            <thead>
                <tr>
                    <th>mode</th>
                    <th>date</th>
                    <th>WPM</th>
                    <th>ACC</th>
                    <th>ERR</th>
                </tr>
            </thead>
            <tbody>
                {% for attemp in attemps %}
                <tr>
                    <td>{{attemp.mode}}</td>
                    <td>{{attemp.attemp_time}}</td>
                    <td>{{attemp.wpm}}</td>
                    <td class="accur">{{attemp.accuracy}}%</td>
                    <td>{{attemp.error_cnt}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

{% block buttons %}

<li class="nav-item">           
    <a class="nav-link {% if not telegram_id %} not_verified {% else %}verified {% endif %}" id="link_telegram" 
    {% if not telegram_id %} href=" {% url "users:link_telegram" %}" target="_blank" {% else %}href="{% url "users:unlink_telegram" %}" {% endif %}" >
        <i class="fa-brands fa-telegram"></i>
    </a>
</li>

<li class="nav-item my-auto">                
    <a class="nav-link " id="logout" href="{% url "users:logout" %}">
        <i class="fa-solid fa-right-from-bracket"></i>
    </a>
</li>
{% endblock buttons %}
{% block script %} 
<script src="{% static "deps/js/profile.js" %}"></script>
{% endblock script %}